package enums;

public enum ChanceCards {
	ADVANCETOBOARDWALK, ADVANCETOGO, ADVANCEILLINOISAVENUE, ADVANCETONEARESTRAILROAD1,
	ADVANCETONEARESTRAILROAD2, ADVANCETONEARESTUTILITY, BANKPAYSYOU, GETOUTOFJAIL, 
	GOBACK3SPACES, GOTOJAIL, MAKEREPAIRSONPROPERTY, SPEEDINGFINE, TRIPTOREADINGRAILROAD,
	ELECTEDCHAIRMAN, BUILDINGLOANMATURES
}
