package enums;

public enum ChanceCards {
	ADVANCE_TO_BOARDWALK, ADVANCE_TO_GO, ADVANCE_ILLINOIS_AVENUE, ADVANCE_TO_STCHARLES_PLACE,
	ADVANCE_TO_NEAREST_RAILROAD_1, ADVANCE_TO_NEAREST_RAILROAD_2, ADVANCE_TO_NEAREST_UTILITY, 
	BANK_PAYS_YOU, GET_OUT_OF_JAIL, GO_BACK_3_SPACES, GO_TO_JAIL, MAKE_REPAIRS_ON_PROPERTY, 
	SPEEDING_FINE, TRIP_TO_READING_RAILROAD, ELECTED_CHAIRMAN, BUILDING_LOAN_MATURES
}
