package enums;

public enum CommunityChestCards {
	ADVANCE_TO_GO, BANK_ERROR, DOCTOR_FEE, SALE_OF_STOCK, GET_OUT_OF_JAIL, GO_TO_JAIL,
	HOLIDAY_FUND, INCOME_TAX, ITS_YOUR_BIRTHDAY, LIFE_INSURANCE_MATURES, HOSPITAL_FEES, 
	SCHOOL_FEES, RECEIVE_CONSULTANCY_FEE, STREET_REPAIR, WIN_BEAUTY_CONTEST, INHERIT_100
}