package enums;

public enum CommunityChestCards {
	ADVANCETOGO, BANKERROR, DOCTORFEE, SALEOFSTOCK, GETOUTOFJAIL, GOTOJAIL,
	HOLIDAYFUND, INCOMETAX, ITSYOURBIRTHDAY, LIFEINSURANCEMATURES, HOSPITALFEES, 
	SCHOOLFEES, RECEIVECONSULTANCYFEE, STREETREPAIR, WINBEAUTYCONTEST, INHERIT100
}